---
- hosts: prod
  become: yes
  tasks:

  - name: Install mysql-server
    apt: name=mysql-server state=latest
  
  - name: Start mysql-server service
    service:
      name: mysql
      state: started
      enabled: true

  - name: Build Docker image
    command: docker build https://raw.githubusercontent.com/MarcAnthonyFanfan/webapp1/master/Dockerfile -t flaskapp
    register: build_result
    changed_when: False
    failed_when: "'Successfully tagged flaskapp:latest' not in build_result.stdout"
  
  - name: Stop webapp1 Docker container if already running
    command: docker stop webapp1
    register: stop_result
    changed_when: "'No such container' not in stop_result.stderr"
    failed_when: False

  - name: Run webapp1 Docker container
    command: docker run --rm -itd --name webapp1 --network host flaskapp bash
    register: run_result
    changed_when: "'already in use' not in run_result.stderr"
    failed_when: False
    ignore_errors: True

  - name: Copy cert.pem over to webapp1 Docker container
    command: docker cp ./certs/cert.pem webapp1:/cert.pem

  - name: Copy key.pem over to webapp1 Docker container
    command: docker cp ./certs/key.pem webapp1:/key.pem

  - name: Set FLASK_ENV variable to production
    command: docker exec webapp1 bash -c 'FLASK_ENV=production'

  - name: Start Flask App
    shell: "(docker exec webapp1 /webapp1/start.sh >>flask.log 2>&1 &)"
    async: 10
    poll: 0