---
- hosts: dev
  become: yes
  tasks:

  - name: Install mysql-server
    apt: name=mysql-server state=latest
  
  - name: Start mysql-server service
    service:
      name: mysql
      state: started
      enabled: true

  - name: Build Docker image
    command: docker build https://raw.githubusercontent.com/MarcAnthonyFanfan/webapp1/master/Dockerfile -t flaskapp
    register: build_result
    changed_when: False
    failed_when: "'Successfully tagged flaskapp:latest' not in build_result.stdout"
  
  - name: Stop webapp1 Docker container if already running
    command: docker stop webapp1
    register: stop_result
    changed_when: "'No such container' not in stop_result.stderr"
    failed_when: False

  - name: Run webapp1 Docker container
    command: docker run --rm -itd --name webapp1 --network host --log-driver=splunk --log-opt splunk-token=eyJraWQiOiJzcGx1bmsuc2VjcmV0IiwiYWxnIjoiSFM1MTIiLCJ2ZXIiOiJ2MiIsInR0eXAiOiJzdGF0aWMifQ.eyJpc3MiOiJtZmFueDIgZnJvbSBERUxMIiwic3ViIjoibWZhbngyIiwiYXVkIjoiRG9ja2VyIiwiaWRwIjoiU3BsdW5rIiwianRpIjoiMzU4MTJhMmEyMjZmNDM5YTU2NDFjNzMxZTMxZDBhM2E0MDU2MzQxZTkzYzU0NjJjOTNjMTlkMGJjODc4ZjgyNiIsImlhdCI6MTU3MjAxODEwNCwiZXhwIjowLCJuYnIiOjE1NzIwMTgxMDR9.QQp7keROdI7bUiMjQbvmam0AOHgW1zuE9s7TJS0yTbF0420FFqeE-rZ67kRIE1ljDZfOALJUbPqMy5hmGG6h9w --log-opt splunk-url=http://192.168.1.88:8000 flaskapp bash
    register: run_result
    changed_when: "'already in use' not in run_result.stderr"
    failed_when: False
    ignore_errors: True

  - name: Copy cert.pem over to webapp1 Docker container
    command: docker cp ./certs/cert.pem webapp1:/cert.pem

  - name: Copy key.pem over to webapp1 Docker container
    command: docker cp ./certs/key.pem webapp1:/key.pem

  - name: Start Flask App
    shell: "(docker exec webapp1 /webapp1/start.sh >/dev/null 2>&1 &)"
    async: 10
    poll: 0