---
- hosts: dev
  become: yes
  tasks:

  - name: Install mysql-server
    apt: name=mysql-server state=latest
  
  - name: Start mysql-server service
    service:
      name: mysql
      state: started
      enabled: true

  - name: Build Docker image
    command: docker build https://raw.githubusercontent.com/MarcAnthonyFanfan/webapp1/master/Dockerfile -t flaskapp
    register: build_result
    changed_when: False
    failed_when: "'Successfully tagged flaskapp:latest' not in build_result.stdout"
  
  - name: Stop webapp1 Docker container if already running
    command: docker stop webapp1
    register: stop_result
    changed_when: "'No such container' not in stop_result.stderr"
    failed_when: False
    
  - name: Run webapp1 Docker container
    command: docker run --rm -itd --name webapp1 --network host flaskapp
    register: run_result
    changed_when: "'already in use' not in run_result.stderr"
    failed_when: False
    ignore_errors: True